<a href="https://colab.research.google.com/github/Jabir-Ahmed-Isse9/full_fraud_detection_project_with_the_team/blob/main/faraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("paysim.csv")

In [3]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [4]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
69853,9,PAYMENT,30681.62,C849962043,0.0,0.0,M64549705,0.0,0.0,0.0,0.0
69854,9,PAYMENT,2866.47,C258151288,0.0,0.0,M1910014593,0.0,0.0,0.0,0.0
69855,9,PAYMENT,2926.88,C145336381,0.0,0.0,M1278169306,0.0,0.0,0.0,0.0
69856,9,PAYMENT,3704.30,C1539334900,0.0,0.0,M1849245575,0.0,0.0,0.0,0.0
69857,9,PAYMENT,248.82,C731155005,0.0,0.0,M495695381,0.0,NaN,NaN,NaN

In [5]:
df.shape

(69858, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69858 entries, 0 to 69857
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   step            69858 non-null  int64
 1   type            69858 non-null  object
 2   amount          69858 non-null  float64
 3   nameOrig        69858 non-null  object
 4   oldbalanceOrg   69858 non-null  float64
 5   newbalanceOrig  69858 non-null  float64
 6   nameDest        69858 non-null  object
 7   oldbalanceDest  69858 non-null  float64
 8   newbalanceDest  69857 non-null  float64
 9   isFraud         69857 non-null  float64
 10  isFlaggedFraud  69857 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 5.9+ MB

In [7]:
new_df=df.copy()

In [8]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [9]:
new_df["oldbalanceDest"].median()

14160.5

In [10]:
new_df["oldbalanceDest"]=new_df["oldbalanceDest"].fillna(new_df["oldbalanceDest"].median())

In [11]:
new_df["newbalanceDest"]=new_df["newbalanceDest"].fillna(new_df["newbalanceDest"].median())

In [12]:
new_df["isFraud"]=new_df["isFraud"].fillna(new_df["isFraud"].mode()[0])

In [13]:
new_df["isFlaggedFraud"]=new_df["isFlaggedFraud"].fillna(new_df["isFlaggedFraud"].mode()[0])

In [14]:
new_df["newbalanceOrig"]=new_df["newbalanceOrig"].fillna(new_df["newbalanceOrig"].mean())

In [15]:
new_df["nameDest"]=new_df["nameDest"].fillna(new_df["nameDest"].mode()[0])

In [16]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [17]:
new_df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
69853,9,PAYMENT,30681.62,C849962043,0.0,0.0,M64549705,0.0,0.00,0.0,0.0
69854,9,PAYMENT,2866.47,C258151288,0.0,0.0,M1910014593,0.0,0.00,0.0,0.0
69855,9,PAYMENT,2926.88,C145336381,0.0,0.0,M1278169306,0.0,0.00,0.0,0.0
69856,9,PAYMENT,3704.30,C1539334900,0.0,0.0,M1849245575,0.0,0.00,0.0,0.0
69857,9,PAYMENT,248.82,C731155005,0.0,0.0,M495695381,0.0,21130.68,0.0,0.0

In [18]:
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [19]:
new_df=new_df.drop_duplicates()

In [20]:
new_df.shape

(69858, 11)

In [21]:
new_df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0.0    69858
Name: count, dtype: int64

In [22]:
# new_df['isFraud']=new_df["isFraud"].str.strip().str.capitalize()
# is_fraud_cleaned=new_df["isFraud"].value_counts()
# display(is_fraud_cleaned)

In [23]:
x=new_df.drop(columns="isFraud")

In [24]:
x

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.00,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.00,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.00,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.00,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...
69853,9,PAYMENT,30681.62,C849962043,0.0,0.00,M64549705,0.0,0.00,0.0
69854,9,PAYMENT,2866.47,C258151288,0.0,0.00,M1910014593,0.0,0.00,0.0
69855,9,PAYMENT,2926.88,C145336381,0.0,0.00,M1278169306,0.0,0.00,0.0
69856,9,PAYMENT,3704.30,C1539334900,0.0,0.00,M1849245575,0.0,0.00,0.0
69857,9,PAYMENT,248.82,C731155005,0.0,0.00,M495695381,0.0,21130.68,0.0

In [25]:
y=new_df["isFraud"]

In [26]:
y

0        0.0
1        0.0
2        1.0
3        1.0
4        0.0
        ...
69853    0.0
69854    0.0
69855    0.0
69856    0.0
69857    0.0
Name: isFraud, Length: 69858, dtype: float64

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [28]:
X_train,X_test,y_train,y_test= train_test_split (
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [29]:
cat=[
 "type",
 "nameOrig",
 "nameDest"

]

In [30]:
num=[
    "step",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",
    "isFlaggedFraud"

]

In [36]:
prepocessing = ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown="ignore"),cat),
    ("num",StandardScaler(),num)
])

In [37]:
logistic = Pipeline([
    ("preprocessor",prepocessing),
    ("model",LogisticRegression())
])

In [38]:
logistic.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model', LogisticRegression())])

In [39]:
y_pred=logistic.predict(X_test)

In [40]:
accuracy=accuracy_score(y_test,y_pred)
precision_scr=precision_score(y_test,y_pred)
recall_scr=recall_score(y_test,y_pred)
f1_scr=f1_score(y_test,y_pred)

print("Accuracy:",accuracy)
print("Precision Score:",precision_scr)
print("Recall Score:",recall_scr)
print("F1 Score:",f1_scr)

Accuracy: 0.998496993987976
Precision Score: 1.0
Recall Score: 0.045454545454545456
F1 Score: 0.08695652173913043

In [51]:
import joblib
joblib.dump(logistic, "logistic_model_for_fraud_detection.joblib")
print("Model saved successfully!")

Model saved successfully!

In [42]:
random = Pipeline([
    ("preprocessor",prepocessing),
    ("model",RandomForestClassifier())
])

In [43]:
random.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model', RandomForestClassifier())])

In [45]:
y_predict=random.predict(X_test)

In [48]:
rf_accuracy = accuracy_score(y_test, y_predict)
rf_precision = precision_score(y_test, y_predict)
rf_recall = recall_score(y_test, y_predict)
rf_f1 = f1_score(y_test, y_predict)

print("===== Random Forest Results =====")
print("Accuracy:", rf_accuracy)
print("Precision Score:", rf_precision)
print("Recall Score:", rf_recall)
print("F1 Score:", rf_f1)

===== Random Forest Results =====
Accuracy: 0.9984254222731177
Precision Score: 0.0
Recall Score: 0.0
F1 Score: 0.0

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [52]:
joblib.dump(random, "random_forest_model_for_fraud_detection.joblib")
print("Model saved successfully!")

Model saved successfully!