<a href="https://colab.research.google.com/github/Jabir-Ahmed-Isse9/full_fraud_detection_project_with_the_team/blob/main/models/faraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("fraud_data.csv")

In [3]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0,0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1,0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0,0

In [4]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.0,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.0,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.0,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.0,C873221189,6510099.11,7360101.63,1,0

In [5]:
df.shape

(6362620, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            object
 2   amount          float64
 3   nameOrig        object
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        object
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), object(3)
memory usage: 534.0+ MB

In [7]:
new_df=df.copy()

In [8]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [9]:
new_df["oldbalanceDest"].median()

132705.66499999998

In [10]:
new_df["oldbalanceDest"]=new_df["oldbalanceDest"].fillna(new_df["oldbalanceDest"].median())

In [11]:
new_df["newbalanceDest"]=new_df["newbalanceDest"].fillna(new_df["newbalanceDest"].median())

In [12]:
new_df = new_df.dropna(subset=["isFraud"])

In [13]:
new_df["isFlaggedFraud"]=new_df["isFlaggedFraud"].fillna(new_df["isFlaggedFraud"].mode()[0])

In [14]:
new_df["newbalanceOrig"]=new_df["newbalanceOrig"].fillna(new_df["newbalanceOrig"].mean())

In [15]:
new_df["nameDest"]=new_df["nameDest"].fillna(new_df["nameDest"].mode()[0])

In [16]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [17]:
new_df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.0,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.0,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.0,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.0,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.0,C873221189,6510099.11,7360101.63,1,0

In [18]:
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [19]:
new_df=new_df.drop_duplicates()

In [20]:
new_df.shape

(6362620, 11)

In [21]:
new_df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0    6362604
1         16
Name: count, dtype: int64

In [22]:
# new_df['isFraud']=new_df["isFraud"].str.strip().str.capitalize()
# is_fraud_cleaned=new_df["isFraud"].value_counts()
# display(is_fraud_cleaned)

In [23]:
x=new_df.drop(columns="isFraud")

In [24]:
x

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...,...
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,0

In [25]:
y=new_df["isFraud"]

In [26]:
y

0          0
1          0
2          1
3          1
4          0
          ..
6362615    1
6362616    1
6362617    1
6362618    1
6362619    1
Name: isFraud, Length: 6362620, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [28]:
X_train,X_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [29]:
cat=[
 "type",
 "nameOrig",
 "nameDest"

]

In [30]:
num=[
    "step",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest",
    "isFlaggedFraud"

]

In [31]:
prepocessing = ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown="ignore"),cat),
    ("num",StandardScaler(),num)
])

In [49]:
logistic = Pipeline([
    ("preprocessor",prepocessing),
    ("model",LogisticRegression(class_weight="balanced"))
])

In [51]:
logistic.fit(X_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model', LogisticRegression(class_weight='balanced'))])

In [52]:
y_pred=logistic.predict(X_test)

In [53]:
accuracy=accuracy_score(y_test,y_pred)
precision_scr=precision_score(y_test,y_pred)
recall_scr=recall_score(y_test,y_pred)
f1_scr=f1_score(y_test,y_pred)

print("Accuracy:",accuracy)
print("Precision Score:",precision_scr)
print("Recall Score:",recall_scr)
print("F1 Score:",f1_scr)

Accuracy: 0.9967639117219007
Precision Score: 0.24234853216739538
Recall Score: 0.7084601339013998
F1 Score: 0.3611542041576171

In [54]:
import joblib
joblib.dump(logistic, "logistic_model_for_fraud_detection.joblib")
print("Model saved successfully!")

Model saved successfully!

In [55]:
random_forest = Pipeline([
    ("preprocessor",prepocessing),
    ("model",RandomForestClassifier(n_estimators=100,class_weight="balanced",max_depth=10, n_jobs=-1))
])

In [56]:
random_forest.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type', 'nameOrig',
                                                   'nameDest']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest',
                                                   'isFlaggedFraud'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced', max_depth=10,
                                        n_jobs=-1))])

In [57]:
y_predict=random_forest.predict(X_test)

In [58]:
rf_accuracy = accuracy_score(y_test, y_predict)
rf_precision = precision_score(y_test, y_predict)
rf_recall = recall_score(y_test, y_predict)
rf_f1 = f1_score(y_test, y_predict)

print("===== Random Forest Results =====")
print("Accuracy:", rf_accuracy)
print("Precision Score:", rf_precision)
print("Recall Score:", rf_recall)
print("F1 Score:", rf_f1)

===== Random Forest Results =====
Accuracy: 0.43432422492620965
Precision Score: 0.0022386311498247212
Recall Score: 0.9829580036518564
F1 Score: 0.004467088758149326

In [ ]:
joblib.dump(random, "random_forest_model_for_fraud_detection.joblib")
print("Model saved successfully!")