<a href="https://colab.research.google.com/github/Jabir-Ahmed-Isse9/full_fraud_detection_project_with_the_team/blob/main/models/faraud_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("fraud_data.csv")

In [3]:
df.head()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.0,0.0,0.0,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.0,0.0,0.0,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.0,0.0,1.0,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.0,0.0,1.0,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.0,0.0,0.0,0.0

In [4]:
df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
450125,19,CASH_OUT,228326.96,C782211031,0.0,0.0,C538433035,2968641.05,3196968.00,0.0,0.0
450126,19,CASH_OUT,26233.86,C403629646,0.0,0.0,C1298110595,291030.95,492893.00,0.0,0.0
450127,19,CASH_OUT,142142.81,C454326032,0.0,0.0,C1945229769,144386.22,286529.03,0.0,0.0
450128,19,CASH_OUT,145866.35,C1287398797,0.0,0.0,C1831572419,757895.36,903761.71,0.0,0.0
450129,19,CASH_OUT,156219.98,C516891362,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(450130, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 450130 entries, 0 to 450129
Data columns (total 11 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   step            450130 non-null  int64
 1   type            450130 non-null  object
 2   amount          450130 non-null  float64
 3   nameOrig        450130 non-null  object
 4   oldbalanceOrg   450129 non-null  float64
 5   newbalanceOrig  450129 non-null  float64
 6   nameDest        450129 non-null  object
 7   oldbalanceDest  450129 non-null  float64
 8   newbalanceDest  450129 non-null  float64
 9   isFraud         450129 non-null  float64
 10  isFlaggedFraud  450129 non-null  float64
dtypes: float64(7), int64(1), object(3)
memory usage: 37.8+ MB

In [7]:
new_df=df.copy()

In [8]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     1
newbalanceOrig    1
nameDest          1
oldbalanceDest    1
newbalanceDest    1
isFraud           1
isFlaggedFraud    1
dtype: int64

In [9]:
new_df["oldbalanceDest"].median()

113245.51

In [10]:
new_df["oldbalanceDest"]=new_df["oldbalanceDest"].fillna(new_df["oldbalanceDest"].median())

In [11]:
new_df["newbalanceDest"]=new_df["newbalanceDest"].fillna(new_df["newbalanceDest"].median())

In [12]:
new_df = new_df.dropna(subset=["isFraud"])

In [13]:
new_df["isFlaggedFraud"]=new_df["isFlaggedFraud"].fillna(new_df["isFlaggedFraud"].mode()[0])

In [14]:
new_df["newbalanceOrig"]=new_df["newbalanceOrig"].fillna(new_df["newbalanceOrig"].mean())

In [15]:
new_df["nameDest"]=new_df["nameDest"].fillna(new_df["nameDest"].mode()[0])

In [16]:
new_df.isnull().sum()

step              0
type              0
amount            0
nameOrig          0
oldbalanceOrg     0
newbalanceOrig    0
nameDest          0
oldbalanceDest    0
newbalanceDest    0
isFraud           0
isFlaggedFraud    0
dtype: int64

In [17]:
new_df.tail()

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFraud,isFlaggedFraud
450124,19,CASH_OUT,147077.56,C516503233,0.0,0.0,C460741314,188623.14,335700.70,0.0,0.0
450125,19,CASH_OUT,228326.96,C782211031,0.0,0.0,C538433035,2968641.05,3196968.00,0.0,0.0
450126,19,CASH_OUT,26233.86,C403629646,0.0,0.0,C1298110595,291030.95,492893.00,0.0,0.0
450127,19,CASH_OUT,142142.81,C454326032,0.0,0.0,C1945229769,144386.22,286529.03,0.0,0.0
450128,19,CASH_OUT,145866.35,C1287398797,0.0,0.0,C1831572419,757895.36,903761.71,0.0,0.0

In [18]:
new_df[new_df.duplicated(keep="last")]

Empty DataFrame
Columns: [step, type, amount, nameOrig, oldbalanceOrg, newbalanceOrig, nameDest, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud]
Index: []

In [19]:
new_df=new_df.drop_duplicates()

In [20]:
new_df.shape

(450129, 11)

In [21]:
new_df["isFlaggedFraud"].value_counts()

isFlaggedFraud
0.0    450129
Name: count, dtype: int64

In [22]:
# new_df['isFraud']=new_df["isFraud"].str.strip().str.capitalize()
# is_fraud_cleaned=new_df["isFraud"].value_counts()
# display(is_fraud_cleaned)

In [23]:
x=new_df.drop(columns="isFraud")

In [24]:
x

,step,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
0,1,PAYMENT,9839.64,C1231006815,170136.0,160296.36,M1979787155,0.00,0.00,0.0
1,1,PAYMENT,1864.28,C1666544295,21249.0,19384.72,M2044282225,0.00,0.00,0.0
2,1,TRANSFER,181.00,C1305486145,181.0,0.00,C553264065,0.00,0.00,0.0
3,1,CASH_OUT,181.00,C840083671,181.0,0.00,C38997010,21182.00,0.00,0.0
4,1,PAYMENT,11668.14,C2048537720,41554.0,29885.86,M1230701703,0.00,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...
450124,19,CASH_OUT,147077.56,C516503233,0.0,0.00,C460741314,188623.14,335700.70,0.0
450125,19,CASH_OUT,228326.96,C782211031,0.0,0.00,C538433035,2968641.05,3196968.00,0.0
450126,19,CASH_OUT,26233.86,C403629646,0.0,0.00,C1298110595,291030.95,492893.00,0.0
450127,19,CASH_OUT,142142.81,C454326032,0.0,0.00,C1945229769,144386.22,286529.03,0.0
450128,19,CASH_OUT,145866.35,C1287398797,0.0,0.00,C1831572419,757895.36,903761.71,0.0

In [25]:
y=new_df["isFraud"]

In [26]:
y

0         0.0
1         0.0
2         1.0
3         1.0
4         0.0
         ...
450124    0.0
450125    0.0
450126    0.0
450127    0.0
450128    0.0
Name: isFraud, Length: 450129, dtype: float64

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [28]:
X_train,X_test,y_train,y_test=train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [29]:
cat = ["type"]

num = [
    "step",
    "amount",
    "oldbalanceOrg",
    "newbalanceOrig",
    "oldbalanceDest",
    "newbalanceDest"
]

In [30]:
prepocessing = ColumnTransformer([
    ("cat",OneHotEncoder(handle_unknown="ignore"),cat),
    ("num",StandardScaler(),num)
])

In [47]:
logistic = Pipeline([
    ("preprocessor", prepocessing),
    ("model", LogisticRegression(
        class_weight={0: 1, 1: 10},
        max_iter=2000,
        solver="lbfgs",
        random_state=42
    ))
])

In [50]:
logistic.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest'])])),
                ('model',
                 LogisticRegression(class_weight={0: 1, 1: 10}, max_iter=2000,
                                    random_state=42))])

In [51]:
fraud_probability = logistic.predict_proba(X_test)[:, 1]
y_pred = (fraud_probability >= 0.90).astype(int)

In [52]:
# evaluation
metrics_score= pd.DataFrame({
    "metrics": ["accuracy","precision","recall","f1"],
    "score": [
        accuracy_score(y_test,y_pred),
        precision_score(y_test,y_pred),
        recall_score(y_test,y_pred),
        f1_score(y_test,y_pred)
    ]
})

In [53]:
metrics_score

     metrics     score
0   accuracy  0.999556
1  precision  0.833333
2     recall  0.113636
3         f1  0.200000

In [54]:
import joblib
joblib.dump(logistic, "logistic_model_for_fraud_detection.joblib")
print("Model saved successfully!")

Model saved successfully!

In [37]:
random_forest = Pipeline([
    ("preprocessor", prepocessing),
    ("model", RandomForestClassifier(
        n_estimators=300,
        class_weight={0: 1, 1: 10},
        min_samples_leaf=5,
        max_features="sqrt",
        n_jobs=-1,
        random_state=42
    ))
])

In [38]:
random_forest.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['type']),
                                                 ('num', StandardScaler(),
                                                  ['step', 'amount',
                                                   'oldbalanceOrg',
                                                   'newbalanceOrig',
                                                   'oldbalanceDest',
                                                   'newbalanceDest'])])),
                ('model',
                 RandomForestClassifier(class_weight={0: 1, 1: 10},
                                        min_samples_leaf=5, n_estimators=300,
                                        n_jobs=-1, random_state=42))])

In [39]:
fraud_probability = random_forest.predict_proba(X_test)[:, 1]
y_predict = (fraud_probability >= 0.50).astype(int)

In [40]:
rf_accuracy = accuracy_score(y_test, y_predict)
rf_precision = precision_score(y_test, y_predict)
rf_recall = recall_score(y_test, y_predict)
rf_f1 = f1_score(y_test, y_predict)

print("===== Random Forest Results =====")
print("Accuracy:", rf_accuracy)
print("Precision Score:", rf_precision)
print("Recall Score:", rf_recall)
print("F1 Score:", rf_f1)

===== Random Forest Results =====
Accuracy: 0.9997111945437984
Precision Score: 0.875
Recall Score: 0.4772727272727273
F1 Score: 0.6176470588235294

In [42]:
joblib.dump(random_forest, "random_forest_model_for_fraud_detection.joblib")
print("Model saved successfully!")

Model saved successfully!